/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.JOptionPane;

/**
 *
 * @author Yeison Romero Salinas
 */
public class Vista_Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Calculadora
     */
    public Vista_Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTF_num1 = new javax.swing.JTextField();
        JTF_num2 = new javax.swing.JTextField();
        JB_multiplicar = new javax.swing.JButton();
        JB_dividir = new javax.swing.JButton();
        JB_sumar = new javax.swing.JButton();
        JB_restar = new javax.swing.JButton();
        JL_resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JB_multiplicar.setText("multiplicar");
        JB_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_multiplicarActionPerformed(evt);
            }
        });

        JB_dividir.setText("dividir");

        JB_sumar.setText("sumar");

        JB_restar.setText("restar");

        JL_resultado.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTF_num1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(JTF_num2))
                        .addGap(26, 26, 26)
                        .addComponent(JL_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JB_multiplicar)
                                .addGap(18, 18, 18)
                                .addComponent(JB_dividir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JB_sumar)
                                .addGap(18, 18, 18)
                                .addComponent(JB_restar)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JTF_num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTF_num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(JL_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_multiplicar)
                    .addComponent(JB_dividir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_sumar)
                    .addComponent(JB_restar))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_multiplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_multiplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Calculadora().setVisible(true);
            }
        });
    }

    /*public String getNumero1(){
        return JTF_num1.getText();
    }
    
    public String getNumero2(){
        return JTF_num2.getText();
    }
    
    public void setResultado(String resultado){
        JL_resultado.setText(resultado);
    }
    
    public void showError(String error){
        JOptionPane.showMessageDialog(this, error, "error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void addListener(ActionListener listener){
        JB_multiplicar.setActionCommand("multiplicar");
        JB_multiplicar.addActionListener(listener);
        
        JB_dividir.setActionCommand("dividir");
        JB_dividir.addActionListener(listener);
        
        JB_sumar.setActionCommand("sumar");
        JB_sumar.addActionListener(listener);
        
        JB_restar.setActionCommand("restar");
        JB_restar.addActionListener(listener);
    }
*/
    public String getNumero1(){
        return JTF_num1.getText();
    }
    
    public String getNumero2(){
        return JTF_num2.getText();
    }
    
    public void setResultado(String resultado){
        JL_resultado.setText(resultado);
    }
    
    public void showError(String error){
        JOptionPane.showMessageDialog(this, error, "error", JOptionPane.WARNING_MESSAGE);
    }
    
    public void addListener(ActionListener listener){
        JB_multiplicar.setActionCommand("mult");
        JB_multiplicar.addActionListener(listener);
        
        JB_dividir.setActionCommand("div");
        JB_dividir.addActionListener(listener);
        
        JB_sumar.setActionCommand("sumar");
        JB_sumar.addActionListener(listener);
        
        JB_restar.setActionCommand("resta");
        JB_restar.addActionListener(listener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_dividir;
    private javax.swing.JButton JB_multiplicar;
    private javax.swing.JButton JB_restar;
    private javax.swing.JButton JB_sumar;
    private javax.swing.JLabel JL_resultado;
    private javax.swing.JTextField JTF_num1;
    private javax.swing.JTextField JTF_num2;
    // End of variables declaration//GEN-END:variables
}
